### ISSUE TITLE
Progress Tracker

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [SaptarshiSarkar12/Java-Complete-Reference#2]
This is a progress tracker keeping track of my learnings :

- [ ] **Part I > The Java Language**
    - [ ] Chapter 1 : The History and Evolution of Java    
    - [ ] Chapter 2 : An Overview of Java
    - [ ] Chapter 3 : Data Types, Variables, and Arrays
    - [ ] Chapter 4 : Operators
    - [ ] Chapter 5 : Control Statements
    - [ ] Chapter 6 : Introducing Classes
    - [ ] Chapter 7 : A Closer Look at Methods and Classes
    - [ ] Chapter 8 : Inheritance
    - [ ] Chapter 9 : Packages and Interfaces 
    - [ ] Chapter 10 : Exception Handling
    - [ ] Chapter 11 : Multithreaded Programming
    - [ ] Chapter 12 : Enumerations, Autoboxing, and Annotations (Metadata)
    - [ ] Chapter 13 : I/O, Applets, and Other Topics
    - [ ] Chapter 14 : Generics
    - [ ] Chapter 15 : Lambda Expressions
- [ ] **Part II > The Java Library**
    - [ ] Chapter 16 : String Handling
    - [ ] Chapter 17 : Exploring java.lang
    - [ ] Chapter 18 : _**java.util**_ Part 1: The Collections Framework
    - [ ] Chapter 19 : **_java.util_** Part 2: More Utility Classes
    - [ ] Chapter 20 : Input/Output: Exploring java.io
    - [ ] Chapter 21 : Exploring NIO
    - [ ] Chapter 22 : Networking
    - [ ] Chapter 23 : The Applet Class
    - [ ] Chapter 24 : Event Handling
    - [ ] Chapter 25 : Introducing the AWT: Working with Windows, Graphics, and Text
    - [ ] Chapter 26 : Using AWT Controls, Layout Managers, and Menus
    - [ ] Chapter 27 : Images
    - [ ] Chapter 28 : The Concurrency Utilities
    - [ ] Chapter 29 : The Stream API
    - [ ] Chapter 30 : Regular Expressions and Other Packages
- [ ] **Part III > Introducing GUI Programming with Swing**
    - [ ] Chapter 31 : Introducing Swing
    - [ ] Chapter 32 : Exploring Swing
    - [ ] Chapter 33 : Introducing Swing Menus
- [ ] **Part IV > Introducing GUI Programming with JavaFX**
    - [ ] Chapter 34 : Introducing JavaFX GUI Programming
    - [ ] Chapter 35 : Exploring JavaFX Controls
    - [ ] Chapter 36 : Introducing JavaFX Menus
- [ ] **Part V > Applying Java**
    - [ ] Chapter 37 : Java Beans
    - [ ] Chapter 38 : Introducing Servlets
    - [ ] Appendix : Using Java’s Documentation Comments

**Comment by jprindus** [comment]
thanks for your great job!!

**Comment by SaptarshiSarkar12** [comment]
> thanks for your great job!!

@jprindus Thank you for looking into the repository.
